### ISSUE TITLE
I have some question about dropout rate

### ISSUE THREAD

**Issue by vanche** [julian121266/RecurrentHighwayNetworks#11]
In the paper, you said "Dropout rates were chosen to be 0.75 for the embedding layer, 0.25 for the input to the gates, 0.25 for the hidden units and 0.75 for the output activations. "
But in the "rhn_train.py" you use 0.25 for embedding layer and 0.75 for input gate.
Why is it different?

**Comment by jzilly** [comment]
Thank you for spotting that. We must have had a mixup of numbers in the paper. The code should be regarded as ground truth. We used dropout rates of 0.25 for the input embedding and the hidden state and 0.75 for the input to the gates and the output embedding.
