### ISSUE TITLE
how long it takes for torch_rhn_enwik8.lua....

### ISSUE THREAD

**Issue by SeekPoint** [julian121266/RecurrentHighwayNetworks#3]
in my gtx 1080, it runs 3days and still going on yet....

**Comment by jzilly** [comment]
Dear loveJasmine,
In our experiment it took around 100 epochs until results did not improve any further for enwik8. Please also note that experiments were not optimized for learning speed. This should allow you to make an educated guess of how far along during training you currently are. 
Best wishes,
Julian

**Comment by SeekPoint** [comment]
thanks, now I am in epoch 34
;)
