### ISSUE TITLE
Reset hidden state

### ISSUE THREAD

**Issue by christopher5106** [julian121266/RecurrentHighwayNetworks#5]
Hi Julian,
When you train over multiple layers 
https://github.com/julian121266/RecurrentHighwayNetworks/blob/master/theano_rhn.py#L225
I'm not sure you really reset the hidden state, since the reset method will correspond to the last layer only. 
Am I wrong ?

**Comment by shimisalant** [comment]
True, good catch.
I'll send a fix.
Thanks!

**Comment by christopher5106** [comment]
By the way, do you get good convergence results on Theano ? Thanks

**Comment by shimisalant** [comment]
Hi Christopher,
Yes, got the same results as in paper for PTB (there's a log in #2 ).
Thanks for pointing this out, please see #6 .
