### ISSUE TITLE
Hyperparameters for the 32M RHN

### ISSUE THREAD

**Issue by tlaurent19** [julian121266/RecurrentHighwayNetworks#7]
Hi Julian,

Could you please provide the (torch) hyperparameters for the 8-layers, 890-units, RHN that leads to  71.2 validation perplexity and 68.5 test perplexity, as published in the paper. Should I take the same setting as in the posted code but just change number of units and number of layers (see below). 

Also, is the negative initial bias for the transfer gate implemented in the torch code (I see it in the tensorflow code but not in the torch code).

local params = {batch_size=20,
                seq_length=35,
                layers=1,
                decay=1.02,
                rnn_size=890,
                dropout_x=0.25,
                dropout_i=0.75,
                dropout_h=0.25,
                dropout_o=0.75,
                init_weight=0.04,
                lr=0.2,
                vocab_size=10000,
                max_epoch=20,
                max_max_epoch=500,
                max_grad_norm=10,
                weight_decay=1e-7,
                recurrence_depth=8}

Thanks,
Thomas

**Comment by jzilly** [comment]
Hi Thomas,

The parameters you attached seem like they should be correct if memory serves me well. Essentially what we did is that we changed the recurrence_depth from 1 to 10 and changed the number of units (rnn_size) such that the number of parameters stays roughly equal to allow for a fair comparison. Many of the other parameters such as sequence length (seq_length) were adopted from Yarin Gal's code.

You are right that the initial_bias seems to have gotten lost when cleaning up the code. As you can check, the torch script for enwik8 does have such an initial bias. I will try to fix that over the weekend such that both scripts have the possibility of an initial bias. 

Thank you for pointing that out!

Best,
Julian

**Comment by flukeskywalker** [comment]
Yes, we used the same parameters and changed the `hidden_size` and `depth`. We used the Tensorflow code for these runs. We have also found that one can reduce the `weight_decay` for better results than the current version.

**Comment by tlaurent19** [comment]
Thanks for the detailed answers. If you have a chance to update the ptb torch code that would be nice.

Best,
Thomas
