### ISSUE TITLE
Run the code with the tensorflow 1.0

### ISSUE THREAD

**Issue by DingkunLong** [julian121266/RecurrentHighwayNetworks#9]
thanks a lot for your code, run your code using the tensorflow version 1.0, 

 from tensorflow.python.ops.nn import rnn
ImportError: cannot import name rnn

another question is: RNNCell = rnn.RNNCell 
AttributeError: 'module' object has no attribute 'RNNCell'
How I need to modify the code?

**Comment by julian121266** [comment]
Hi DingkunLong,
Yes with tensorflow 1.0 a bit of the syntax changed. We made two branches for this case, one (master) for pre 1.0 tensorflow and one for tensorflow 1.0. 
Please let me know whether the other branch (called tensorflow_1.0_branch) works for you.

**Comment by dendisuhubdy** [comment]
@countback see here https://github.com/julian121266/RecurrentHighwayNetworks/pull/15
